install.packages("caret")
library(caret)
train<-read.csv("Train.csv", header = TRUE, fileEncoding = "UTF-8-BOM")
str(train)
head(train)
summary(train)
sum(!complete.cases(train))
set.seed(42)
idx<-createDataPartition(train$Reached.on.Time_Y.N, p=0.7)
idx
ds_train<-train[idx$Resample1, ]
ds_test<-train[-idx$Resample1, ]
ds_train$Reached.on.Time_Y.N<-as.factor(ds_train$Reached.on.Time_Y.N)
ds_test$Reached.on.Time_Y.N<-as.factor(ds_test$Reached.on.Time_Y.N)
md_first<-glm(Reached.on.Time_Y.N~., family=binomial, data=ds_train)
pred_first<-predict(object = md_first, newdata = ds_test, type = 'response')
pred_result<-ifelse(pred_first>=0.5, 1, 0)
pred_result<-as.factor(pred_result)
confusionMatrix(data=pred_result, reference = ds_test$Reached.on.Time_Y.N)
install.packages("e1071")
library(e1071)
md_second<-svm(Reached.on.Time_Y.N~., data=ds_train)
pred_second<-predict(object = md_second, newdata = ds_test, type='response')
pred_second<-as.factor(pred_second)
confusionMatrix(data=pred_second, reference = ds_test$Reached.on.Time_Y.N)
ds_test$prediction<-predict(object = md_second, newdata = ds_test, type='response')
ds_result<-ds_test[c("ID", "prediction")]
write.csv(ds_result, "submit.csv", row.names = FALSE)
