library(caret)
train<-read.csv("Train.csv", header = TRUE, fileEncoding = "UTF-8-BOM")
str(train)
head(train)
summary(train)
sum(!complete.cases(train))
set.seed(42)
idx<-createDataPartition(train$Reached.on.Time_Y.N, p=0.7)
dtrain<-train[idx$Resample1, ]
dtest<-train[-idx$Resample1, ]
dtrain$Reached.on.Time_Y.N<-as.factor(dtrain$Reached.on.Time_Y.N)
dtest$Reached.on.Time_Y.N<-as.factor(dtest$Reached.on.Time_Y.N)
md_first<-glm(Reached.on.Time_Y.N~., family = binomial, data=dtrain)
pred_first<-predict(object = md_first, newdata = dtest, type = "response")
pred_result<-ifelse(pred_first>=0.5, 1, 0)
pred_result<-as.factor(pred_result)
confusionMatrix(data=pred_result, reference = dtest$Reached.on.Time_Y.N)
library(e1071)
md_second<-svm(Reached.on.Time_Y.N~., data = dtrain)
pred_second<-predict(object = md_second, newdata = dtest, type='response')
confusionMatrix(data=pred_second, reference = dtest$Reached.on.Time_Y.N)
library(randomForest)
md_third<-randomForest(Reached.on.Time_Y.N~., data=dtrain, ntree=300, do.trace=TRUE)
pred_third<-predict(md_third, newdata = dtest, type="response")
confusionMatrix(data=pred_third, reference = dtest$Reached.on.Time_Y.N)
dtest$prediction<-predict(object = md_second, newdata = dtest, type='response')
result<-dtest[c("ID", "prediction")]
write.csv(result, "003000755.csv", row.names = FALSE)
